# Site settings
title: "james wallace"
description: "james wallace - 2025"
email: "t4st email"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jameswallace99.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: "jekyll/minima@d4d779a" # This is an example, choose your theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown

#navigation
# _config.yml
# ... (rest of your settings) ...

# --------------------------
# NAVIGATION CONFIGURATION
# --------------------------
header_links:
  - title: Home
    url: /
  - title: About Me
    url: /about/

hide_site_feed_link: true # hide rss feed link from footer


