# Site settings
title: "james wallace"
description: "test description"
email: "t4st email"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jameswallace99.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: "jekyll/minima@1e8a445" # This is an example, choose your theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
