# Site settings
title: "james wallace"
description: "james wallace - 2025"
url: "https://jameswallace99.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: "jekyll/minima@d4d779a" # This is an example, choose your theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  hide_site_feed_link = true


# Build settings
markdown: kramdown

#navigation
# _config.yml
# ... (rest of your settings) ...

# --------------------------
# NAVIGATION CONFIGURATION
# --------------------------
header_links:
  - title: Home
    url: /
  - title: About Me
    url: /about/



